### ISSUE TITLE
weewx APRS crash

### ISSUE THREAD

**Issue by dukeofdoom** [cavedon/weewx-aprs#7]
Running weewx 5.0.2 and the aprs extension seems to be crashing weewx.  
I didnt run in to this problem on weewx 3.x. 

is there a new version of this extension?  It was very helpful on my old station.

Mar 05 23:38:58 hampi weewxd[4297]: INFO weewx.manager: Starting backfill of daily summaries
Mar 05 23:38:58 hampi weewxd[4297]: INFO weewx.manager: Daily summaries up to date
Mar 05 23:38:58 hampi weewxd[4297]: DEBUG weewx.drivers.vantage: Getting archive packets since 2024-03-05 23:00:00 EST (1709697600)
Mar 05 23:38:58 hampi weewxd[4297]: DEBUG weewx.drivers.vantage: Successfully woke up Vantage console
Mar 05 23:38:58 hampi weewxd[4297]: DEBUG weewx.drivers.vantage: Retrieving 1 page(s); starting index= 1
Mar 05 23:38:59 hampi weewxd[4297]: INFO weewx.engine: Main loop exiting. Shutting engine down.
Mar 05 23:38:59 hampi weewxd[4297]: DEBUG weewx.restx: Shut down PWSWeather thread.
Mar 05 23:38:59 hampi weewxd[4297]: DEBUG weewx.restx: Shut down Wunderground-PWS thread.
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__: Caught unrecoverable exception:
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****  'wind_average'
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****  Traceback (most recent call last):
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd.py", line 166, in main
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      engine.run()
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 174, in run
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 241, in dispatchEvent
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      callback(event)
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 610, in startup
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      self._catchup(self.engine.console.genStartupRecords)
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 726, in _catchup
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      self.engine.dispatchEvent(weewx.Event(weewx.NEW_ARCHIVE_RECORD,
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 241, in dispatchEvent
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      callback(event)
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****    File "/etc/weewx/bin/user/aprs.py", line 80, in _handle_new_archive_record
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****      data.append('g%03.f' % record['wind_average'])
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****                             ~~~~~~^^^^^^^^^^^^^^^^
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****  KeyError: 'wind_average'
Mar 05 23:38:59 hampi weewxd[4297]: CRITICAL __main__:     ****  Exiting.

**Comment by savagebread** [comment]
Resolved in this PR with a catch, can you confirm this is working for you? @dukeofdoom 
https://github.com/cavedon/weewx-aprs/pull/8/changes#diff-aa30face32d32b9126f4232a42796011c2c8caf0cf8faffca1b71ad465bb35cbR82
